

import { Dot, ArrowRight} from "lucide-react";
import { useQuoteModal } from "../../../../../context/QuoteModalContext";

export default function BatteryHero() {
  const { openQuoteModal } = useQuoteModal();

  // const badges = [
  //   {
  //     icon: <Award className="w-4 h-4 text-yellow-400" />,
  //     text: "CEC-Accredited Installers",
  //   },
  //   {
  //     icon: <ShieldCheck className="w-4 h-4 text-green-400" />,
  //     text: "25-Yr Performance Warranty",
  //   },
  //   {
  //     icon: <Zap className="w-4 h-4 text-amber-400" />,
  //     text: "Tier-1 Solar Hardware",
  //   },
  //   {
  //     icon: <DollarSign className="w-4 h-4 text-emerald-400" />,
  //     text: "$0 Deposit Financing",
  //   },
  // ];

  return (
    <section className="relative h-screen w-full overflow-hidden " id="solar">

      <img src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR3bvfMuCfWvc7ZpPyAvbuypjXknQmr1vP9ZSwa4ucmEw&s=10" alt="Solar panel installation"  className="absolute inset-0 w-full h-full object-cover opacity-85 object-center" />

      <div className="absolute inset-0 bg-linear-to-r from-slate-950/90  to-slate-950/70" />
      <div className="relative z-10 max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 grid grid-cols-1 md:grid-cols-2 gap-7 py-8 sm:py-14 lg:py-14">
        <div className="max-w-3xl text-white space-y-5">
          <p className="font-bold text-xs sm:text-sm uppercase tracking-wider px-3.5 py-1.5 rounded-full inline-flex items-center gap-1 bg-amber-500/20 text-amber-300 border border-amber-400/40 backdrop-blur-md">
            <Dot strokeWidth={8} className ="w-5 h-5 text-amber-400 animate-pulse" />
            <span>Explore Home Batteries</span>
          </p>
          <h1 className="text-3xl sm:text-4xl lg:text-5xl font-bold font-serif leading-tight">
            Store solar  <span className="bg-linear-to-r from-yellow-300 via-amber-300 to-green-400 bg-clip-text text-transparent">  energy today and use it </span> when you need it. </h1>
          <p className="text-base sm:text-lg text-white font-medium leading-relaxed max-w-2xl">
            Home batteries store surplus electricity generated by your solar panels so you can use that energy later, especially during the evening and night.
            They can help reduce your dependence on grid electricity, provide backup power for selected loads, and make better use of the solar energy your system produces.
          </p>

          <div className="pt-4">
            <button onClick={() => openQuoteModal()} type="button" className="bg-linear-to-r from-amber-500 to-orange-500 hover:from-amber-600 hover:to-orange-600 text-white font-bold text-base py-3 px-4 rounded-full transition-all duration-300 shadow-lg hover:shadow-orange-500/20 inline-flex items-center gap-2 cursor-pointer active:scale-95 group">
              <span>Get Your Free Solar Quote</span>
              <ArrowRight className="w-4 h-4 transition-transform duration-300 ease-in-out group-hover:translate-x-1.5"/>
            </button>
          </div>
        </div>

        <div className="flex items-center justify-center"><img src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSeHSCN6BhLLbB_0rUxVBHBD0wTcAsi1JOB-QmTOZWi9g&s=10" className=" rounded-4xl border border-white shadow-2xl/60 max-w-100 max-h-100 shadow-white" alt="solar battery image" /></div>
      </div>
    </section>
  );
}         