import {  Gauge, PanelsTopLeft,  Home,  CheckCircle2 } from "lucide-react";
import { motion } from "framer-motion";
export default function InverterCapacity() {
  const points = [
    {
      number: "01",
      title: "Inverter Capacity Is Measured in kW",
      description:
        "An inverter's capacity is usually expressed in kilowatts (kW). It indicates the maximum amount of AC power the inverter can deliver at a given time.",
      icon: Gauge,
    },
    {
      number: "02",
      title: "Panel Size and Inverter Size Are Different",
      description:
        "The total capacity of your solar panels does not always need to exactly match the inverter capacity. The system is designed around expected solar production and the inverter's operating limits.",
      icon: PanelsTopLeft,
    },
    {
      number: "03",
      title: "Your Energy Needs Matter",
      description:
        "Inverter selection depends on factors such as the size of the solar array, household electricity demand, expected solar production and whether a battery is included.",
      icon: Home,
    },
    {
      number: "04",
      title: "The Right Size Helps Performance",
      description:
        "An appropriately sized inverter can efficiently handle the electricity generated by the solar panels without being unnecessarily oversized or undersized.",
      icon: CheckCircle2,
    },
  ];

  return (
    <section className="w-full bg-slate-50 py-14">
      <div className=" max-w-7xl mx-auto px-6 lg:px-8">

        <div className="max-w-4xl ml-4">
          <p className="mb-3 text-sm font-semibold uppercase tracking-wider text-amber-500">Inverter Capacity
          </p>
          <h2 className="font-serif text-3xl font-bold text-slate-950 md:text-3xl lg:text-4xl">Understanding Inverter Size and Capacity
          </h2>
          <p className="mt-6 text-base leading-7 text-slate-600 md:text-lg">The size of a solar inverter determines how much electricity it can convert from DC power produced by the solar panels into AC power for your home. Choosing the right capacity helps the solar system operate effectively and match the home's energy requirements.
          </p>
        </div>

        <div className="max-w-6xl mt-12 px-3">
          <div className="mb-8 flex justify-center">
           <span className="text-sm font-semibold uppercase tracking-wider text-amber-500">What Determines Inverter Size?
            </span>
          </div>

          <div>
            {points.map((point) => {
              const Icon = point.icon;
              return (
                <motion.div  
                initial={{opacity:0 , x : -20}}
                whileInView={{ opacity: 1 , x : 0 }}
                viewport={{ once: true}}
                transition={{ duration: 0.6}}
                key={point.number} className="group flex gap-3 border-b border-slate-200 py-8   md:items-start">
                  <div className="w-20 text-3xl font-bold text-slate-200 transition-colors group-hover:text-amber-400">
                    {point.number}
                  </div>
                 <div className="w-60 flex items-start gap-3">
                    <Icon className="mt-1 h-5 w-5 shrink-0 text-amber-500" />
                    <h3 className="text-lg font-semibold leading-7 text-slate-900">
                      {point.title}
                    </h3>
                  </div>
                  <p className="max-w-2xl text-base leading-7 text-slate-600">
                    {point.description}
                  </p>
                </motion.div>
              );
            })}
          </div>
        </div>

        <div className="mt-14 flex flex-col gap-6 border-l-4 border-amber-500 bg-slate-50 px-6 py-4 md:px-8">
          <div>
            <h3 className="text-lg font-semibold text-slate-900">Why does inverter sizing matter?</h3>
            <p className="mt-2 max-w-3xl leading-7 text-slate-600"> The right inverter size allows the system to efficiently manage the electricity produced by your solar panels while meeting the energy requirements of your home.
            </p>
          </div>
        </div>
      </div>
    </section>
  );
}